[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", path = "../../core/client" }
jsonrpc-core = "13.2.0"
node-primitives = { path = "../primitives" }
sr-primitives = { path = "../../core/sr-primitives" }
srml-contracts-rpc = { path = "../../srml/contracts/rpc/" }
srml-system-rpc = { path = "../../srml/system/rpc/" }
txpoolapi = { package = "substrate-transaction-pool-api", path = "../../core/transaction-pool/api" }
